{
 "title": "Latency Metrics Through The Stack",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  { "title": "CPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU Load",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    { "expr": "quobyte_server_cpu_load" }
   ]
  },
  {
   "title": "GC Safepoint",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "rate(quobyte_jvm_gc_safepoint_count[5m])"
    }
   ]
  },
  {
   "title": "GC Total time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "rate(quobyte_jvm_gc_safepoint_total_time_millis[5m])"
    }
   ]
  },
  {
   "title": "JVM Scheduling Delay",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "histogram_quantile(0.9999, sum(rate(quobyte_jvm_scheduling_delay_micros_bucket{service_type=\"quobyte-metadata\"}[5m])) by (le, service_uuid))"
    }
   ]
  },
  {
   "title": "Backpressure / admission control",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 }
  },
  {
   "title": "RPC Blocked Connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "rate(quobyte_rpc_server_total_blocked_connections[5m])"
    }
   ]
  },
  {
   "title": "RPC Global Blocked Connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "expr": "rate(quobyte_rpc_server_total_global_blocked_connections[5m])"
    }
   ]
  },
  { "title": "Metadata", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "Long-tail latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "targets": [
    {
     "expr": "histogram_quantile(0.9999, sum(rate(quobyte_db_replication_backup_processing_latency_micros_bucket{service_type=\"quobyte-metadata\"}[5m])) by (le, service_uuid)) "
    }
   ]
  },
  { "title": "Metadata read operations", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 } },
  {
   "title": "Metadata read latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 36 },
   "targets": [
    {
     "expr": "histogram_quantile(0.9999, sum(rate(quobyte_lowlevel_metadata_read_latency_nanos_bucket[5m])) by (le, service_uuid))"
    }
   ]
  },
  {
   "title": "Executor processing time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 36 },
   "targets": [
    {
     "expr": "histogram_quantile(0.9999, sum(rate(quobyte_executor_processing_time_micros_bucket{service_type=\"quobyte-metadata\"}[5m])) by (le, service_uuid))"
    }
   ]
  },
  {
   "title": "Lookup latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 44 },
   "targets": [
    {
     "expr": "histogram_quantile(0.9999, sum(rate(quobyte_db_lookup_latency_micros_bucket{service_type=\"quobyte-metadata\"}[5m])) by (le, service_uuid))"
    }
   ]
  },
  { "title": "Metadata write operations", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 52 } },
  {
   "title": "Metadata write latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 53 },
   "targets": [
    {
     "expr": "histogram_quantile(0.9999, sum(rate(quobyte_lowlevel_metadata_write_latency_nanos_bucket[5m])) by (le, service_uuid))"
    }
   ]
  },
  {
   "title": "Replicate quorum latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 53 },
   "targets": [
    {
     "expr": "histogram_quantile(0.9999, sum(rate(quobyte_db_replication_replicate_quorum_latency_micros_bucket{service_type=\"quobyte-metadata\"}[5m])) by (le, service_uuid))"
    }
   ]
  },
  {
   "title": "Metadata writes to local disk",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 61 },
   "targets": [
    {
     "expr": "histogram_quantile(0.9999, sum(rate(quobyte_db_storage_write_latency_micros_bucket{service_type=\"quobyte-metadata\"}[5m])) by (le, service_uuid))"
    }
   ]
  },
  {
   "title": "RPCs to backups",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 61 },
   "targets": [
    {
     "expr": "histogram_quantile(0.9999, sum(rate(quobyte_db_replication_backup_roundtrip_latency_micros_bucket{service_type=\"quobyte-metadata\"}[5m])) by (le, service_uuid))"
    }
   ]
  },
  {
   "title": "Backup processing latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 69 },
   "targets": [
    {
     "expr": "histogram_quantile(0.9999, sum(rate(quobyte_db_replication_backup_processing_latency_micros_bucket{service_type=\"quobyte-metadata\"}[5m])) by (le, service_uuid))"
    }
   ]
  },
  { "title": "RAM", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 77 } },
  {
   "title": "Page fault count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 78 },
   "targets": [
    {
     "expr": "rate(quobyte_service_major_page_fault_count[5m])"
    }
   ]
  },
  { "title": "Primary Failover", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 86 } },
  {
   "title": "Replication primary device ID",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 87 },
   "targets": [
    {
     "expr": "quobyte_db_replication_primary_device_id"
    }
   ]
  },
  { "title": "Other", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 95 } },
  {
   "title": "Queue full",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 96 },
   "targets": [
    { "expr": "quobyte_queues_queue_full" }
   ]
  },
  {
   "title": "Busy threads",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 96 },
   "targets": [
    { "expr": "quobyte_executor_busy_threads" }
   ]
  },
  { "title": "Data read operations", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 104 } },
  {
   "title": "Client read latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 105 },
   "targets": [
    {
     "expr": "histogram_quantile(0.9999, sum(rate(quobyte_client_read_latency_nanos_bucket[5m])) by (le))"
    }
   ]
  },
  {
   "title": "File open latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 105 },
   "targets": [
    {
     "expr": "histogram_quantile(0.9999, sum(rate(quobyte_osd_storage_file_open_latency_micros_bucket{service_type=\"quobyte-data\"}[5m])) by (le, service_uuid))"
    }
   ]
  },
  {
   "title": "Primary reset",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 113 },
   "targets": [
    {
     "expr": "histogram_quantile(0.9999, sum(rate(quobyte_osd_replication_primary_reset_micros_bucket{service_type=\"quobyte-data\"}[5m])) by (le, service_uuid))"
    }
   ]
  },
  {
   "title": "Primary storage read latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 113 },
   "targets": [
    {
     "expr": "histogram_quantile(0.9999, sum(rate(quobyte_osd_read_latency_micros_bucket[5m])) by (le))"
    }
   ]
  },
  {
   "title": "4k read latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 121 },
   "targets": [
    {
     "expr": "histogram_quantile(0.9999, sum(rate(quobyte_osd_storage_4k_read_latency_micros_bucket[5m])) by (le))"
    }
   ]
  },
  { "title": "Data write operations", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 129 } },
  {
   "title": "Client write latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 130 },
   "targets": [
    {
     "expr": "histogram_quantile(0.9999, sum(rate(quobyte_client_write_latency_nanos_bucket[5m])) by (le))"
    }
   ]
  },
  {
   "title": "Primary storage write latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 130 },
   "targets": [
    {
     "expr": "histogram_quantile(0.9999, sum(rate(quobyte_osd_write_latency_micros_bucket{service_type=\"quobyte-data\"}[5m])) by (le, service_uuid))"
    }
   ]
  },
  {
   "title": "Backup replica writes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 138 },
   "targets": [
    {
     "expr": "histogram_quantile(0.9999, sum(rate(quobyte_osd_backup_write_micros_bucket{service_type=\"quobyte-data\"}[5m])) by (le, service_uuid))"
    }
   ]
  },
  {
   "title": "4k write latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 138 },
   "targets": [
    {
     "expr": "histogram_quantile(0.9999, sum(rate(quobyte_osd_storage_4k_write_latency_micros_bucket{service_type=\"quobyte-data\"}[5m])) by (le, service_uuid))"
    }
   ]
  }
 ]
}