{
 "title": "Quobyte Dashboard 3.x",
 "description": "Get a quick overview of your Quobyte Storage",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "ds", "label": "datasource", "query": "prometheus" },
   { "name": "setup", "label": "Cluster", "query": { "query": "label_values(quobyte_cluster)" } },
   {
    "name": "device_type",
    "label": "Device Types",
    "query": {
     "query": "label_values(device_hardware_type)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Capacity Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Usage of Data ${device_type}s",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 1 },
   "repeat": "device_type",
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(quobyte_device_usage_bytes{service_type=\"quobyte-data\", quobyte_cluster=\"$setup\", device_hardware_type=\"$device_type\"}) / sum(quobyte_device_capacity_bytes{service_type=\"quobyte-data\", quobyte_cluster=\"$setup\", device_hardware_type=\"$device_type\"})"
    }
   ]
  },
  {
   "title": "Trend of Data Capacity (${device_type}s)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 9, "x": 3, "y": 1 },
   "repeat": "device_type",
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(quobyte_device_usage_bytes{service_type=\"quobyte-data\", quobyte_cluster=\"$setup\", device_hardware_type=\"$device_type\"})"
    },
    {
     "expr": "sum(quobyte_device_capacity_bytes{service_type=\"quobyte-data\", quobyte_cluster=\"$setup\", device_hardware_type=\"$device_type\"})"
    }
   ]
  },
  {
   "title": "Devices with errors",
   "type": "table",
   "gridPos": { "h": 12, "w": 11, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "  max(quobyte_osd_storage_io_error{quobyte_cluster=\"$setup\"}) by (device_id, __name__) > 0 OR\n  max(quobyte_osd_storage_crc_error{quobyte_cluster=\"$setup\"}) by (device_id, __name__) > 0 OR\n  max(quobyte_device_smart_command_timeout{quobyte_cluster=\"$setup\"}) by (device_id, __name__) > 0 OR\n  max(quobyte_device_smart_crc_error_count{quobyte_cluster=\"$setup\"}) by (device_id, __name__) > 0 OR\n  max(quobyte_device_smart_current_pending_sector{quobyte_cluster=\"$setup\"}) by (device_id, __name__) > 0 OR\n  max(quobyte_device_smart_device_life_left{quobyte_cluster=\"$setup\"}) by (device_id, __name__) < 20 OR\n  max(quobyte_device_smart_offline_uncorrectable{quobyte_cluster=\"$setup\"}) by (device_id, __name__) > 0 OR\n  max(quobyte_device_smart_reallocated_sector_ct{quobyte_cluster=\"$setup\"}) by (device_id, __name__) > 0 OR\n  max(quobyte_device_smart_reported_uncorrect{quobyte_cluster=\"$setup\"}) by (device_id, __name__) > 0"
    }
   ]
  },
  {
   "title": "Utilization of Data ${device_type}s",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 9 },
   "repeat": "device_type",
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "quantile(0.5, rate(quobyte_osd_storage_busy_time_millis{quobyte_cluster=\"$setup\", device_hardware_type=\"$device_type\"}[5m])) / 1000 "
    }
   ]
  },
  {
   "title": "Utilization of Data ${device_type}s",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 9, "x": 3, "y": 13 },
   "repeat": "device_type",
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "quantile(0.5, irate(quobyte_osd_storage_busy_time_millis{quobyte_cluster=\"$setup\", device_hardware_type=\"$device_type\"}[5m])) / 1000",
     "legendFormat": "50th quantile"
    },
    {
     "expr": "quantile(0.9, irate(quobyte_osd_storage_busy_time_millis{quobyte_cluster=\"$setup\", device_hardware_type=\"$device_type\"}[5m])) / 1000",
     "legendFormat": "90th quantile"
    },
    {
     "expr": "quantile(0.99, irate(quobyte_osd_storage_busy_time_millis{quobyte_cluster=\"$setup\", device_hardware_type=\"$device_type\"}[5m])) / 1000",
     "legendFormat": "99th quantile"
    },
    {
     "expr": "quantile(1, irate(quobyte_osd_storage_busy_time_millis{quobyte_cluster=\"$setup\", device_hardware_type=\"$device_type\"}[5m])) / 1000",
     "legendFormat": "max"
    }
   ]
  },
  {
   "title": "Usage in 30d",
   "type": "stat",
   "description": "Based on growth of last 2 weeks",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 17 },
   "repeat": "device_type",
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(predict_linear(quobyte_device_usage_bytes{service_type=\"quobyte-data\", quobyte_cluster=\"$setup\", device_hardware_type=\"$device_type\"}[2w], 30 * 86400))"
    }
   ]
  },
  {
   "title": "Usage of Metadata Devices",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(quobyte_device_usage_bytes{service_type=\"quobyte-metadata\", quobyte_cluster=\"$setup\"}) / sum(quobyte_device_capacity_bytes{service_type=\"quobyte-metadata\", quobyte_cluster=\"$setup\"})"
    }
   ]
  },
  {
   "title": "Trend of Metadata Capacity",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 20, "x": 3, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(quobyte_device_usage_bytes{service_type=\"quobyte-metadata\", quobyte_cluster=\"$setup\"}) "
    },
    {
     "expr": "sum(quobyte_device_capacity_bytes{service_type=\"quobyte-metadata\", quobyte_cluster=\"$setup\"})"
    }
   ]
  },
  {
   "title": "Service restart indicator",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 23, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(quobyte_metrics_global_starttime_millis{service_type!~\"quobyte-client\"}[5m])) by (hostname,service_type) > 0",
     "legendFormat": "{{hostname}}: {{service_type}}"
    }
   ]
  },
  {
   "title": "Metadata Operations",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 23, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(irate(quobyte_metadata_operations_total{quobyte_cluster=\"$setup\"}[5m])) by (op)",
     "legendFormat": "{{op}}"
    }
   ]
  },
  {
   "title": "Data Operations",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 23, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(irate(quobyte_scheduler_finished_count{quobyte_cluster=\"$setup\"}[5m])) by (priority)",
     "legendFormat": "{{priority}}"
    }
   ]
  },
  {
   "title": "Client",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 52 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Client Read Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(irate(quobyte_client_read_latency_nanos_bucket{quobyte_cluster=\"$setup\", service_type=\"quobyte-client\"}[5m])) by (le))",
     "legendFormat": "50th quantile"
    },
    {
     "expr": "histogram_quantile(0.7, sum(irate(quobyte_client_read_latency_nanos_bucket{quobyte_cluster=\"$setup\", service_type=\"quobyte-client\"}[5m])) by (le))",
     "legendFormat": "70th quantile"
    },
    {
     "expr": "histogram_quantile(0.90, sum(irate(quobyte_client_read_latency_nanos_bucket{quobyte_cluster=\"$setup\", service_type=\"quobyte-client\"}[5m])) by (le))",
     "legendFormat": "90th quantile"
    },
    {
     "expr": "histogram_quantile(0.99, sum(irate(quobyte_client_read_latency_nanos_bucket{quobyte_cluster=\"$setup\", service_type=\"quobyte-client\"}[5m])) by (le))",
     "legendFormat": "99th quantile"
    },
    {
     "expr": "histogram_quantile(0.999, sum(irate(quobyte_client_read_latency_nanos_bucket{quobyte_cluster=\"$setup\", service_type=\"quobyte-client\"}[5m])) by (le))",
     "legendFormat": "99.9th quantile"
    },
    {
     "expr": "histogram_quantile(1, sum(irate(quobyte_client_read_latency_nanos_bucket{quobyte_cluster=\"$setup\", service_type=\"quobyte-client\"}[5m])) by (le))",
     "legendFormat": "max"
    }
   ]
  },
  {
   "title": "Client Write Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 12, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(irate(quobyte_client_write_latency_nanos_bucket{quobyte_cluster=\"$setup\", service_type=\"quobyte-client\"}[5m])) by (le))",
     "legendFormat": "50th quantile"
    },
    {
     "expr": "histogram_quantile(0.7, sum(irate(quobyte_client_write_latency_nanos_bucket{quobyte_cluster=\"$setup\", service_type=\"quobyte-client\"}[5m])) by (le))",
     "legendFormat": "70th quantile"
    },
    {
     "expr": "histogram_quantile(0.90, sum(irate(quobyte_client_write_latency_nanos_bucket{quobyte_cluster=\"$setup\", service_type=\"quobyte-client\"}[5m])) by (le))",
     "legendFormat": "90th quantile"
    },
    {
     "expr": "histogram_quantile(0.99, sum(irate(quobyte_client_write_latency_nanos_bucket{quobyte_cluster=\"$setup\", service_type=\"quobyte-client\"}[5m])) by (le))",
     "legendFormat": "99th quantile"
    },
    {
     "expr": "histogram_quantile(0.999, sum(irate(quobyte_client_write_latency_nanos_bucket{quobyte_cluster=\"$setup\", service_type=\"quobyte-client\"}[5m])) by (le))",
     "legendFormat": "99.9th quantile"
    },
    {
     "expr": "histogram_quantile(1, sum(irate(quobyte_client_write_latency_nanos_bucket{quobyte_cluster=\"$setup\", service_type=\"quobyte-client\"}[5m])) by (le))",
     "legendFormat": "max"
    }
   ]
  },
  {
   "title": "Client Storage Read Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(irate(quobyte_client_storage_read_latency_nanos_bucket{quobyte_cluster=\"$setup\", service_type=\"quobyte-client\"}[5m])) by (le))",
     "legendFormat": "50th quantile"
    },
    {
     "expr": "histogram_quantile(0.7, sum(irate(quobyte_client_storage_read_latency_nanos_bucket{quobyte_cluster=\"$setup\", service_type=\"quobyte-client\"}[5m])) by (le))",
     "legendFormat": "70th quantile"
    },
    {
     "expr": "histogram_quantile(0.90, sum(irate(quobyte_client_storage_read_latency_nanos_bucket{quobyte_cluster=\"$setup\", service_type=\"quobyte-client\"}[5m])) by (le))",
     "legendFormat": "90th quantile"
    },
    {
     "expr": "histogram_quantile(0.99, sum(irate(quobyte_client_storage_read_latency_nanos_bucket{quobyte_cluster=\"$setup\", service_type=\"quobyte-client\"}[5m])) by (le))",
     "legendFormat": "99th quantile"
    },
    {
     "expr": "histogram_quantile(0.999, sum(irate(quobyte_client_storage_read_latency_nanos_bucket{quobyte_cluster=\"$setup\", service_type=\"quobyte-client\"}[5m])) by (le))",
     "legendFormat": "99.9th quantile"
    },
    {
     "expr": "histogram_quantile(1, sum(irate(quobyte_client_storage_read_latency_nanos_bucket{quobyte_cluster=\"$setup\", service_type=\"quobyte-client\"}[5m])) by (le))",
     "legendFormat": "max"
    }
   ]
  },
  {
   "title": "Client Storage Write Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 12, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(irate(quobyte_client_storage_write_latency_nanos_bucket{quobyte_cluster=\"$setup\", service_type=\"quobyte-client\"}[5m])) by (le))",
     "legendFormat": "50th quantile"
    },
    {
     "expr": "histogram_quantile(0.7, sum(irate(quobyte_client_storage_write_latency_nanos_bucket{quobyte_cluster=\"$setup\", service_type=\"quobyte-client\"}[5m])) by (le))",
     "legendFormat": "70th quantile"
    },
    {
     "expr": "histogram_quantile(0.90, sum(irate(quobyte_client_storage_write_latency_nanos_bucket{quobyte_cluster=\"$setup\", service_type=\"quobyte-client\"}[5m])) by (le))",
     "legendFormat": "90th quantile"
    },
    {
     "expr": "histogram_quantile(0.99, sum(irate(quobyte_client_storage_write_latency_nanos_bucket{quobyte_cluster=\"$setup\", service_type=\"quobyte-client\"}[5m])) by (le))",
     "legendFormat": "99th quantile"
    },
    {
     "expr": "histogram_quantile(0.999, sum(irate(quobyte_client_storage_write_latency_nanos_bucket{quobyte_cluster=\"$setup\", service_type=\"quobyte-client\"}[5m])) by (le))",
     "legendFormat": "99.9th quantile"
    },
    {
     "expr": "histogram_quantile(1, sum(irate(quobyte_client_storage_write_latency_nanos_bucket{quobyte_cluster=\"$setup\", service_type=\"quobyte-client\"}[5m])) by (le))",
     "legendFormat": "max"
    }
   ]
  },
  {
   "title": "Data Performance",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 69 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Read Throughput per Host",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(irate(quobyte_osd_storage_data_read_bytes{quobyte_cluster=\"$setup\"}[5m])) by (hostname)",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "Write Throughput per Host",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 11, "x": 12, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(irate(quobyte_osd_storage_data_written_bytes{quobyte_cluster=\"$setup\"}[5m])) by (hostname)",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "Read IOs per Host",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 76 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "sum(irate(quobyte_osd_storage_read_operations{quobyte_cluster=\"$setup\"}[5m])) by (hostname)",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "Write IOs per Host",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 11, "x": 12, "y": 76 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "sum(irate(quobyte_osd_storage_write_operations{quobyte_cluster=\"$setup\"}[5m])) by (hostname)",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "Read IO Latency",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 82 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(irate(quobyte_osd_storage_4k_read_latency_micros_bucket{quobyte_cluster=\"$setup\"}[5m])) by (le))",
     "legendFormat": "50th quantile"
    },
    {
     "expr": "histogram_quantile(0.7, sum(irate(quobyte_osd_storage_4k_read_latency_micros_bucket{quobyte_cluster=\"$setup\"}[5m])) by (le))",
     "legendFormat": "70th quantile"
    },
    {
     "expr": "histogram_quantile(0.9, sum(irate(quobyte_osd_storage_4k_read_latency_micros_bucket{quobyte_cluster=\"$setup\"}[5m])) by (le))",
     "legendFormat": "90th quantile"
    },
    {
     "expr": "histogram_quantile(0.99, sum(irate(quobyte_osd_storage_4k_read_latency_micros_bucket{quobyte_cluster=\"$setup\"}[5m])) by (le))",
     "legendFormat": "99th quantile"
    },
    {
     "expr": "histogram_quantile(0.999, sum(irate(quobyte_osd_storage_4k_read_latency_micros_bucket{quobyte_cluster=\"$setup\"}[5m])) by (le))",
     "legendFormat": "99.9th quantile"
    },
    {
     "expr": "histogram_quantile(1, sum(irate(quobyte_osd_storage_4k_read_latency_micros_bucket{quobyte_cluster=\"$setup\"}[5m])) by (le))",
     "legendFormat": "max"
    }
   ]
  },
  {
   "title": "Write IO Latency",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 11, "x": 12, "y": 82 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(irate(quobyte_osd_storage_4k_write_latency_micros_bucket{quobyte_cluster=\"$setup\"}[5m])) by (le))",
     "legendFormat": "50th quantile"
    },
    {
     "expr": "histogram_quantile(0.7, sum(irate(quobyte_osd_storage_4k_write_latency_micros_bucket{quobyte_cluster=\"$setup\"}[5m])) by (le))",
     "legendFormat": "70th quantile"
    },
    {
     "expr": "histogram_quantile(0.9, sum(irate(quobyte_osd_storage_4k_write_latency_micros_bucket{quobyte_cluster=\"$setup\"}[5m])) by (le))",
     "legendFormat": "90th quantile"
    },
    {
     "expr": "histogram_quantile(0.99, sum(irate(quobyte_osd_storage_4k_write_latency_micros_bucket{quobyte_cluster=\"$setup\"}[5m])) by (le))",
     "legendFormat": "99th quantile"
    },
    {
     "expr": "histogram_quantile(0.999, sum(irate(quobyte_osd_storage_4k_write_latency_micros_bucket{quobyte_cluster=\"$setup\"}[5m])) by (le))",
     "legendFormat": "99.9th quantile"
    },
    {
     "expr": "histogram_quantile(1, sum(irate(quobyte_osd_storage_4k_write_latency_micros_bucket{quobyte_cluster=\"$setup\"}[5m])) by (le))",
     "legendFormat": "max"
    }
   ]
  },
  {
   "title": "Device Read latency ($device_type)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 88 },
   "repeat": "device_type",
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(irate(quobyte_osd_storage_device_read_latency_micros_bucket{quobyte_cluster=\"$setup\", device_hardware_type=\"$device_type\"}[5m])) by (le))",
     "legendFormat": "50th quantile"
    },
    {
     "expr": "histogram_quantile(0.7, sum(irate(quobyte_osd_storage_device_read_latency_micros_bucket{quobyte_cluster=\"$setup\", device_hardware_type=\"$device_type\"}[5m])) by (le))",
     "legendFormat": "70th quantile"
    },
    {
     "expr": "histogram_quantile(0.90, sum(irate(quobyte_osd_storage_device_read_latency_micros_bucket{quobyte_cluster=\"$setup\", device_hardware_type=\"$device_type\"}[5m])) by (le))",
     "legendFormat": "90th quantile"
    },
    {
     "expr": "histogram_quantile(0.99, sum(irate(osd:storage:device_read_latency_bucket{quobyte_cluster=\"$setup\", device_hardware_type=\"$device_type\"}[5m])) by (le))",
     "legendFormat": "99th quantile"
    },
    {
     "expr": "histogram_quantile(0.999, sum(irate(quobyte_osd_storage_device_read_latency_micros_bucket{quobyte_cluster=\"$setup\", device_hardware_type=\"$device_type\"}[5m])) by (le))",
     "legendFormat": "99.9th quantile"
    },
    {
     "expr": "histogram_quantile(1, sum(irate(quobyte_osd_storage_device_read_latency_micros_bucket{quobyte_cluster=\"$setup\", device_hardware_type=\"$device_type\"}[5m])) by (le))",
     "legendFormat": "max"
    }
   ]
  },
  {
   "title": "Device Write latency ($device_type)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 11, "x": 12, "y": 88 },
   "repeat": "device_type",
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(irate(quobyte_osd_storage_device_write_latency_micros_bucket{quobyte_cluster=\"$setup\", device_hardware_type=\"$device_type\"}[5m])) by (le))",
     "legendFormat": "50th quantile"
    },
    {
     "expr": "histogram_quantile(0.7, sum(irate(quobyte_osd_storage_device_write_latency_micros_bucket{quobyte_cluster=\"$setup\", device_hardware_type=\"$device_type\"}[5m])) by (le))",
     "legendFormat": "70th quantile"
    },
    {
     "expr": "histogram_quantile(0.9, sum(irate(quobyte_osd_storage_device_write_latency_micros_bucket{quobyte_cluster=\"$setup\", device_hardware_type=\"$device_type\"}[5m])) by (le))",
     "legendFormat": "90th quantile"
    },
    {
     "expr": "histogram_quantile(0.99, sum(irate(quobyte_osd_storage_device_write_latency_micros_bucket{quobyte_cluster=\"$setup\", device_hardware_type=\"$device_type\"}[5m])) by (le))",
     "legendFormat": "99th quantile"
    },
    {
     "expr": "histogram_quantile(0.999, sum(irate(quobyte_osd_storage_device_write_latency_micros_bucket{quobyte_cluster=\"$setup\", device_hardware_type=\"$device_type\"}[5m])) by (le))",
     "legendFormat": "99.9th quantile"
    },
    {
     "expr": "histogram_quantile(1, sum(irate(quobyte_osd_storage_device_write_latency_micros_bucket{quobyte_cluster=\"$setup\", device_hardware_type=\"$device_type\"}[5m])) by (le))",
     "legendFormat": "max"
    }
   ]
  },
  {
   "title": "FileOpenLatency latency ($device_type)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 100 },
   "repeat": "device_type",
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(irate(quobyte_osd_storage_file_open_latency_micros_bucket{quobyte_cluster=\"$setup\", device_hardware_type=\"$device_type\"}[5m])) by (le))",
     "legendFormat": "50th quantile"
    },
    {
     "expr": "histogram_quantile(0.75, sum(irate(quobyte_osd_storage_file_open_latency_micros_bucket{quobyte_cluster=\"$setup\", device_hardware_type=\"$device_type\"}[5m])) by (le))",
     "legendFormat": "75th quantile"
    },
    {
     "expr": "histogram_quantile(0.90, sum(irate(quobyte_osd_storage_file_open_latency_micros_bucket{quobyte_cluster=\"$setup\", device_hardware_type=\"$device_type\"}[5m])) by (le))",
     "legendFormat": "90th quantile"
    },
    {
     "expr": "histogram_quantile(0.99, sum(irate(quobyte_osd_storage_file_open_latency_micros_bucket{quobyte_cluster=\"$setup\", device_hardware_type=\"$device_type\"}[5m])) by (le))",
     "legendFormat": "99th quantile"
    },
    {
     "expr": "histogram_quantile(0.999, sum(irate(quobyte_osd_storage_file_open_latency_micros_bucket{quobyte_cluster=\"$setup\", device_hardware_type=\"$device_type\"}[5m])) by (le))",
     "legendFormat": "99.9th quantile"
    },
    {
     "expr": "histogram_quantile(1, sum(irate(quobyte_osd_storage_file_open_latency_micros_bucket{quobyte_cluster=\"$setup\", device_hardware_type=\"$device_type\"}[5m])) by (le))",
     "legendFormat": "max"
    },
    {
     "expr": "sum(irate(quobyte_osd_storage_file_open_latency_micros_count{device_hardware_type=\"$device_type\"}[5m])) > 0",
     "legendFormat": "file open rate"
    }
   ]
  },
  {
   "title": "Device Sync latency ($device_type)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 108 },
   "repeat": "device_type",
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(irate(quobyte_osd_storage_sync_latency_micros_bucket{quobyte_cluster=\"$setup\", device_hardware_type=\"$device_type\"}[5m])) by (le))",
     "legendFormat": "50th quantile"
    },
    {
     "expr": "histogram_quantile(0.7, sum(irate(quobyte_osd_storage_sync_latency_micros_bucket{quobyte_cluster=\"$setup\", device_hardware_type=\"$device_type\"}[5m])) by (le))",
     "legendFormat": "70th quantile"
    },
    {
     "expr": "histogram_quantile(0.9, sum(irate(quobyte_osd_storage_sync_latency_micros_bucket{quobyte_cluster=\"$setup\", device_hardware_type=\"$device_type\"}[5m])) by (le))",
     "legendFormat": "90th quantile"
    },
    {
     "expr": "histogram_quantile(0.99, sum(irate(quobyte_osd_storage_sync_latency_micros_bucket{quobyte_cluster=\"$setup\", device_hardware_type=\"$device_type\"}[5m])) by (le))",
     "legendFormat": "99th quantile"
    },
    {
     "expr": "histogram_quantile(0.999, sum(irate(quobyte_osd_storage_sync_latency_micros_bucket{quobyte_cluster=\"$setup\", device_hardware_type=\"$device_type\"}[5m])) by (le))",
     "legendFormat": "99.9th quantile"
    },
    {
     "expr": "histogram_quantile(1, sum(irate(quobyte_osd_storage_sync_latency_micros_bucket{quobyte_cluster=\"$setup\", device_hardware_type=\"$device_type\"}[5m])) by (le))",
     "legendFormat": "max"
    }
   ]
  },
  {
   "title": "Metadata file segment create latency",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 23, "x": 0, "y": 114 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(irate(quobyte_metadata_segment_placement_latency_micros_bucket{quobyte_cluster=\"$setup\"}[5m])) by (le))",
     "legendFormat": "50th quantile"
    },
    {
     "expr": "histogram_quantile(0.7, sum(irate(quobyte_metadata_segment_placement_latency_micros_bucket{quobyte_cluster=\"$setup\"}[5m])) by (le))",
     "legendFormat": "70th quantile"
    },
    {
     "expr": "histogram_quantile(0.9, sum(irate(quobyte_metadata_segment_placement_latency_micros_bucket{quobyte_cluster=\"$setup\"}[5m])) by (le))",
     "legendFormat": "90th quantile"
    },
    {
     "expr": "histogram_quantile(0.99, sum(irate(quobyte_metadata_segment_placement_latency_micros_bucket{quobyte_cluster=\"$setup\"}[5m])) by (le))",
     "legendFormat": "99th quantile"
    },
    {
     "expr": "histogram_quantile(0.999, sum(irate(quobyte_metadata_segment_placement_latency_micros_bucket{quobyte_cluster=\"$setup\"}[5m])) by (le))",
     "legendFormat": "99.9th quantile"
    },
    {
     "expr": "histogram_quantile(1, sum(irate(quobyte_metadata_segment_placement_latency_micros_bucket{quobyte_cluster=\"$setup\"}[5m])) by (le))",
     "legendFormat": "max"
    }
   ]
  },
  {
   "title": "System IO",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 23, "x": 0, "y": 120 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(irate(quobyte_osd_storage_data_read_scrub_bytes{quobyte_cluster=\"$setup\"}[5m])) > 0",
     "legendFormat": "scrub read"
    },
    {
     "expr": "sum(irate(quobyte_osd_storage_data_read_maintenance_bytes{quobyte_cluster=\"$setup\"}[5m])) > 0",
     "legendFormat": "maintenance read"
    },
    {
     "expr": "sum(irate(quobyte_osd_storage_data_written_maintenance_bytes{quobyte_cluster=\"$setup\"}[5m])) > 0",
     "legendFormat": "maintenance written "
    }
   ]
  },
  {
   "title": "Scrub latency",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 23, "x": 0, "y": 126 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(irate(quobyte_osd_maintenance_micros_bucket{op=\"checkObject\", quobyte_cluster=\"$setup\"}[5m])) by (le))",
     "legendFormat": "50th quantile"
    },
    {
     "expr": "histogram_quantile(0.7, sum(irate(quobyte_osd_maintenance_micros_bucket{op=\"checkObject\", quobyte_cluster=\"$setup\"}[5m])) by (le))",
     "legendFormat": "70th quantile"
    },
    {
     "expr": "histogram_quantile(0.90, sum(irate(quobyte_osd_maintenance_micros_bucket{op=\"checkObject\",quobyte_cluster=\"$setup\"}[5m])) by (le))",
     "legendFormat": "90th quantile"
    },
    {
     "expr": "histogram_quantile(0.99, sum(irate(quobyte_osd_maintenance_micros_bucket{op=\"checkObject\", quobyte_cluster=\"$setup\"}[5m])) by (le))",
     "legendFormat": "99th quantile"
    },
    {
     "expr": "histogram_quantile(0.999, sum(irate(quobyte_osd_maintenance_micros_bucket{op=\"checkObject\", quobyte_cluster=\"$setup\"}[5m])) by (le))",
     "legendFormat": "99.9th quantile"
    },
    {
     "expr": "histogram_quantile(1, sum(irate(quobyte_osd_maintenance_micros_bucket{op=\"checkObject\", quobyte_cluster=\"$setup\"}[5m])) by (le))",
     "legendFormat": "max"
    }
   ]
  },
  {
   "title": "Metadata Performance",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 132 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Metadata Operation Latency",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 133 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(irate(quobyte_metadata_operations_latency_micros_bucket{quobyte_cluster=\"$setup\"}[5m])) by (le))",
     "legendFormat": "50th quantile"
    },
    {
     "expr": "histogram_quantile(0.7, sum(irate(quobyte_metadata_operations_latency_micros_bucket{quobyte_cluster=\"$setup\"}[5m])) by (le))",
     "legendFormat": "70th quantile"
    },
    {
     "expr": "histogram_quantile(0.9, sum(irate(quobyte_metadata_operations_latency_micros_bucket{quobyte_cluster=\"$setup\"}[5m])) by (le))",
     "legendFormat": "90th quantile"
    },
    {
     "expr": "histogram_quantile(0.99, sum(irate(quobyte_metadata_operations_latency_micros_bucket{quobyte_cluster=\"$setup\"}[5m])) by (le))",
     "legendFormat": "99th quantile"
    },
    {
     "expr": "histogram_quantile(0.999, sum(irate(quobyte_metadata_operations_latency_micros_bucket{quobyte_cluster=\"$setup\"}[5m])) by (le))",
     "legendFormat": "99.9th quantile"
    },
    {
     "expr": "histogram_quantile(1, sum(irate(quobyte_metadata_operations_latency_micros_bucket{quobyte_cluster=\"$setup\"}[5m])) by (le))",
     "legendFormat": "max"
    }
   ]
  },
  {
   "title": "Metadata Operations",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 11, "x": 12, "y": 133 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(irate(quobyte_metadata_operations_total[5m])) by (tenant_uuid)",
     "legendFormat": "Tenant {{tenant_uuid}}"
    }
   ]
  },
  {
   "title": "Service",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 139 },
   "targets": [
    {}
   ]
  },
  {
   "title": "CPU load",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 23, "x": 0, "y": 140 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg(quobyte_server_cpu_load{quobyte_cluster=\"$setup\"}) by (hostname)",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "Host Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 146 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg(quobyte_server_memory_free_bytes{quobyte_cluster=\"$setup\"}) by (hostname) / avg(quobyte_server_memory_total_bytes{quobyte_cluster=\"$setup\"}) by(hostname)",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "RPC Traffic server",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 11, "x": 12, "y": 146 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "irate(quobyte_rpc_server_bytes_tx_bytes{quobyte_cluster=\"$setup\", service_type=\"quobyte-data\"}[5m])",
     "legendFormat": "{{hostname}} sent"
    },
    {
     "expr": "-irate(quobyte_rpc_server_bytes_rx_bytes{quobyte_cluster=\"$setup\", service_type=\"quobyte-data\"}[5m])",
     "legendFormat": "{{hostname}} recvd"
    }
   ]
  },
  {
   "title": "RPC Traffic client",
   "type": "graph",
   "gridPos": { "h": 6, "w": 11, "x": 12, "y": 152 },
   "yaxes": [
    { "format": "Bps", "label": "data rate (+ tx, - rx)" }
   ],
   "targets": [
    {
     "expr": "sum(irate(quobyte_rpc_client_bytes_tx{quobyte_cluster=\"$setup\"}[5m]))",
     "legendFormat": "{{hostname}} sent"
    },
    {
     "expr": "-sum(irate(quobyte_rpc_client_bytes_rx{quobyte_cluster=\"$setup\"}[5m])) ",
     "legendFormat": "{{hostname}} recvd"
    }
   ]
  }
 ]
}